config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'
  get  'static_pages/about'

  get 'sessions/new'
  get '/signup', to:'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :profiles
  resources :microposts

  get 'matchings/index'
  post '/matchings', to: 'matchings#create'
  delete 'matchings/destroy'

  resources :messages, :only => [:create]

  mount ActionCable.server => '/cable'

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  default_scope -> { order(created_at: :desc) }

  def self.search(search)
    if search
      Profile.where(['content LIKE ?', "%#{search}%"])
    else
      Profile.all
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :logged_in_user

  def new
    @profile = Profile.new
  end

  def create
    @user = current_user
    @profile = @user.create_profile(profile_params)
   if @profile.save
     flash[:success] = "Profile created!"
     redirect_to root_url
   else
     render 'static_pages/home'
   end
  end

  def index
    @profiles = Profile.all
    # @profiles = Profile.all.page(params[:page])
  end

  def destroy
    @profile.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  def edit
    @profile = current_user.profile
  end

  def update
  end

  def search
    @profiles = Profile.search(params[:search])
  end

  private

    def profile_params
      params.require(:profile).permit(:content, :Related_links, :carrer, :portfolio, :role)
    end

    def correct_user
      @profile = current_user.profile.find_by(id: params[:id])
      redirect_to root_url if @profile.nil?
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :content %>
  <%= f.text_field :content , class: 'form-control' %>

  <%= f.label :Related_links %>
  <%= f.text_field :Related_links , class: 'form-control' %>

  <%= f.label :carrer %>
  <%= f.text_field :carrer , class: 'form-contorol' %>

  <%= f.label :portfolio  %>
  <%= f.text_field :portfolio , class: 'form-control' %>

  <%= f.submit "Profile Post", class: "btn btn-primary" %>
<% end %>

app/views/profiles/_profile.html.erb
<li id="profile-<%= profile.id %>">
  <%= link_to gravatar_for(profile.user, size: 50), profile.user %>
  <span class="user"><%= link_to profile.user.name, profile.user %></span>

  <span class="Related_links"><%= profile.Related_links %></span>
  <span class="carrer"><%= profile.carrer %></span>
  <span class="portfolio"><%= profile.portfolio %></span> --> %>
  <span class="content"><%= profile.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(profile.created_at) %> ago.
  </span>
  <% if current_user?(profile.user) %>
    <%= link_to "delete", profile, method: :delete,
                                     data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/profiles/edit.html.erb
<% provide(:title, 'Profile Setting') %>
<h1>Profile Setting</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
     <%= render 'form' %>
  </div>
</div>

app/views/profiles/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<p>user search</p>
<%= form_tag(profiles_path, :method => 'get' ) do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>

<ul class="users">
  <% @profiles.each do |profiles| %>
    <li>
       <% render profiles %>
    </li>
  <% end %>
</ul>

app/views/profiles/new.html.erb
<% provide(:title, 'New Profile') %>
<h1>New Profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
     <%= render 'form' %>
  </div>
</div>