config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/help'
  get  'static_pages/about'

  get 'sessions/new'
  get '/signup', to:'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :profiles
  resources :microposts

  get 'matchings/index'
  post '/matchings', to: 'matchings#create'
  delete 'matchings/destroy'

  resources :messages, :only => [:create]

  mount ActionCable.server => '/cable'

end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 500 }

  has_many :matchings
  has_many :matching_users, through: :matchings, source: 'user'

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
   before_action :logged_in_user, only: [:create, :destroy, :edit]
   before_action :correct_user,   only: :destroy

   def new
     @micropost = Micropost.new
   end

   def create
     @micropost = current_user.microposts.build(micropost_params)
     if !(current_user.role == "entrepreneur")
       render root_url
     elsif @micropost.save
       flash[:success] = "Micropost created!"
       redirect_to root_path
     else
       render 'static_pages/home'
     end
   end

   def index
     @microposts = Micropost.page(params[:page])
   end

   def destroy
     @micropost.destroy
     flash[:success] = "Micropost deleted"
     redirect_to request.referrer || root_url
   end

   def edit
   end

   private
      def micropost_params
        params.require(:micropost).permit(:content)
      end

      def correct_user
        @micropost = current_user.microposts.find_by(id: params[:id])
        redirect_to root_url if @micropost.nil?
      end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>

　<%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(micropost.created_at) %> ago.
        <% if current_user?(micropost.user) %>
          <%= link_to "delete", micropost, method: :delete,
                                           data: { confirm: "You sure?" } %>
        <% end %>
    </span>

    <% if logged_in? %>
      <% unless current_user.role == "entrepreneur" %>
         <% if !micropost.matching_users.include?(current_user) %>
            <%= link_to matchings_path(micropost_id: micropost.id, user_id2: micropost.user_id), method: :post do %>
              <%= image_tag 'icons/star-empty.png', :size =>'20x20', class: 'topic-index-icon' %>
            <% end %>

         <% else %>
            <%= link_to matchings_destroy_path(micropost_id: micropost.id, user_id2: micropost.user_id), method: :delete do %>
              <%= image_tag 'icons/star-yellow.png', :size =>'20x20', class: 'topic-index-icon' %>
            <% end %>
         <% end %>
     <% end %>
    <% end %>


</li>

app/views/microposts/index.html.erb
<% provide(:title, 'All posts') %>
<h1>All posts</h1>

<ul class="users">
  <% @microposts.each do |microposts| %>
   <%= render microposts %>
  <% end %>
</ul>

<%= paginate @microposts %>

app/views/microposts/new.html.erb
<% provide(:title, 'New Post') %>
<h1>New Post</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
     <%= render 'form' %>
  </div>
</div>